### ISSUE TITLE
Track Meta tasks for GA

### ISSUE THREAD

**Issue by sruti1312** [opensearch-project/performance-analyzer#25]
Copy task list from opensearch-project/opensearch-plugins#41
Here is a meta issue for all plugins to track items which have to be taken care of between RC1 and GA for all the plugins.

- [x] Plugin branching strategy - created 1.0 and 1.x branches
- [x]  Backward compatibility testing Update REST resources to follow new OpenSearch naming convention #14
- [x] ~~DCO checks - should be done by infra~~ From infra team(@peterzhuamazon), DCO check will not be included for GA release
- [x] ~~Design Documentation - not finalized - see [here](https://github.com/opensearch-project/opensearch-plugins/issues/42)~~ Removed, added for 1.1.0 instead
- [x]  Broken links check
- [x]  Standardize labels
- [x]  README.md, etc
- [x]  Release Tags
- [x]  Release notes
- [x]  Public Documentation
- [x]  Clean up branches
- [x]  Issue and PR templates Depends on https://github.com/opensearch-project/.github/pull/18
- [x]  CI workflows
- [x] ~~Plugins dependencies from Maven~~ Not for GA because plugins would need to build from 1.0 release versions of those dependencies that don’t exist yet.
- [x]  Test coverage reporting
- [x]  License header checks
- [x]  Plugin artifact names
- [x]  Branch protection rules Will be handled by others - details in the issue [here](https://github.com/opensearch-project/opensearch-plugins/issues/52) -> requires admin privilege
